# a mybinder.org-ready environment for demoing jupyterlab_pygments
# this environment may also be used locally on Linux/MacOS/Windows, e.g.
#
#   conda env update --file binder/environment.yml
#   conda activate jupyterlab-pygments-demo
#
name: jupyterlab-pygments-demo

channels:
  - conda-forge

dependencies:
  # runtime dependencies
  - python >=3.12,<3.13.0a0
  - jupyterlab >=4,<5.0.0a0
  # labextension build dependencies
  - nodejs >=20,<21
  - pip
  - wheel
